name: Deploy Node App to Vercel

on:
  push:
    branches:
      - main # Adjust to your main branch
  pull_request:
    branches:
      - main # Adjust to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your preferred Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build # Or your framework-specific build command, e.g., next build or vite build
        env:
          CI: false # Correct issue with cra builds
          NODE_ENV: production # Set node environment

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Vercel API token
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Vercel organization ID
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Vercel project ID
          github-comment: false
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: |
            your-domain.com
            www.your-domain.com

      - name: Send Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: danger
          SLACK_MESSAGE: 'Vercel deployment failed for ${{ github.repository }}'
          SLACK_TITLE: 'Deployment Failed'