name: Deploy Node.js App to Vercel

on:
  push:
    branches:
      - main # Change to your main branch
  pull_request:
    branches:
      - main # Change to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Use the latest LTS version

      - name: Install dependencies
        id: install-dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm install
          update-snapshots: false  # Prevent snapshot updates for clean builds
          working-directory: ./ # Change if your package.json is in a subdirectory

      - name: Build application
        id: build-application
        run: |
          npm run build # Or your specific build command (e.g., npm run build, yarn build)
        env:
          NODE_ENV: production
          # Add any other environment variables needed for your build

      - name: Deploy to Vercel
        id: vercel-deploy
        uses: vercel/vercel-action@v0.15.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Your Vercel token stored as a GitHub secret
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Your Vercel Org ID stored as a GitHub secret
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Your Vercel Project ID stored as a GitHub secret
          github-comment: false
          scope: ${{ secrets.VERCEL_ORG_ID }} # Optional: set the scope

      - name: Post Deployment Notification (Slack - Optional)
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
          SLACK_TITLE: "Deployment Status"
          SLACK_MESSAGE: |
            Deployment to Vercel finished with status: ${{ job.status }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref }}
            Workflow: ${{ github.workflow }}
            Repository: ${{ github.repository }}