name: Deploy to Vercel

on:
  push:
    branches:
      - main # or your main branch
  pull_request:
    branches:
      - main # or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your preferred Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Or your specific build command, e.g., `npm run build:prod`
        env:
          CI: false

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./ # Adjust if your project is in a subdirectory
          vercel-args: '--prod' # or any other vercel deployment args

      - name: Send Slack Notification (Optional)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: danger
          SLACK_TITLE: "Vercel Deployment Failed"
          SLACK_MESSAGE: "Deployment to Vercel failed. Check the workflow logs for details."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}